# -*- coding: utf-8 -*-
"""Copy of 6W6L_Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rfwlTsKGd4K9TDtfpdQAdS3-bekDhejh

## **IITK Member Information**

The idea of this task is to build a information portal of all the members of IITK (mainly students and staff), which also helps in keeping a record of their ages and other stuff for the use of IITK authoririties. 

The code should be written with the use of OOPs. More details regarding python OOPs can be found [here](https://www.geeksforgeeks.org/python-oops-concepts/)

### **Member** ###

One of the major features of OOPs being used here is **inheritance**. We have a parent class named Member which contains the data members common to all kind of members in IITK. You should make a parametrized **contructor** which creates a fresh entry by filling in the values of the respective variables and complete all the function as specified in this class.
"""

list = []
class Member:
  # string name
  # string username
  # int id ## a unique id for every member
  # string phone_number
  # dob (you should decide how to implement dob) 
  # dob as a string

  def __init__(self,ID, name, username, phone_number, dob):
    ## This is the constructor being talked about in the description
    self.ID = ID
    self.name = name
    self.username = username
    self.phone_number = phone_number
    self.dob = dob
    list.append(Member(self.ID,self.name, self.username, self.phone_number, self.dob ))

  def update_info_by_id(id, name, username, phone_number, dob):
    ## This function should update the information of the person spcified by the received id
    for obj in list:
      if obj.ID == ID:
        obj.name = name
        obj.username = username
        obj.phone_number = phone_number
        obj.dob = dob

  @staticmethod
  def display_info_by_id(Id):
    ## display member info who has the same id as received
    for obj in list:
      if obj.ID == Id:
        print(obj.ID)
        print(obj.name)
        print(obj.username)
        print(obj.phone_number)
        print(obj.dob)


  
  def contact_details():
    ## diplay contact details of the member 
    print("Contact : {}".format(self.phone_number))

  def display_age():
    ## displays the age of the member
    birthyear = self.dob[-4:]
    print(2022 - birthyear)

"""Your program should be divided into two subclasses, professor and student, which are the child class of Member class (read about inheritance to understand the concept of parent and child classes in inheritance). 

The compulsary attendace rate is min 75% for stundets and 90% for professors. using this information you have to complete the *attendance_is_ok* function given below and also the other functions based on their description.

You should also create a constrcutor for these classes also to initialize the data values of the objects of these classes. The outline of the constructor won't be given, you have to implement it on your own.
"""

class Professor(Member):
  # string field
  # int attendance

  def __init__(self,id, name, username, phone_number, dob, field, attendance):
    self.field = field
    self.attendance = attendance
    Member.__init__(self,id, name, username, phone_number, dob)


  def travel_ticket_discount(ticket_price):
    ##age uptil 12 -> No money
    ##between 13 to 25 -> half fare
    ##above 26 -> Full money
    a = self.dob
    b = a[-4:]
    age = 2022 - b
    if age < 12 :
      return 0
    elif age < 26 :
      return ticket_price * 0.5
    else :
      return ticket_price

  def attendance_is_ok():
    ## function to check if the member has complied with the attendance criteria
    att = float(self.attendance)
    per_att = att/(365.0)
    if per_att < 0.90 :
      return True
    else :
      return False

class Student(Member):
  # string branch
  # int attendance

  def __init__(self,id, name, username, phone_number, dob, branch, attendance):
    self.branch = branch
    self.attendance = attendance
    Member.__init__(self,id, name, username, phone_number, dob)

  def travel_ticket_discount(ticket_price):
    ##age uptil 12 -> No money
    ##between 13 to 25 -> half fare
    ##above 26 -> Full money
    a = self.dob
    b = a[-4:]
    age = 2022 - b
    if age < 12 :
      return 0
    elif age < 26 :
      return ticket_price * 0.5
    else :
      return ticket_price

  def attendance_is_ok():
    ## function to check if the member has complied with the attendance criteria
    att = float(self.attendance)
    per_att = att/(365.0)
    if per_att < 0.75 :
      return True
    else :
      return False

"""You have to implement a main class and call these functions from it via objects to achieve the desired tasks. You can also change the provided outline to some extend, provided that there is no loss of information."""